// Placeholder images from placehold.co (free). We replace them with real
// downloaded photos later. The color in the URL is a hex code without "#".
const img = (label, bg) =>
  `https://placehold.co/600x800/${bg}/FFFFFF?text=${encodeURIComponent(label)}`;

const CLOTHING_SIZES = ["XS", "S", "M", "L", "XL"];
const SHOE_SIZES = ["38", "39", "40", "41", "42", "43"];
const KIDS_SIZES = ["4Y", "6Y", "8Y", "10Y"];
const ONE_SIZE = ["One Size"];

// Each entry only lists what is different. The seeder fills in SKU and images.
const productData = [
  {
    name: "Oversized Hoodie",
    category: "Men", subcategory: "Hoodies",
    price: 59.99, discountPrice: 44.99,
    colors: ["Black", "Lavender", "Teal"], sizes: CLOTHING_SIZES,
    materials: "80% cotton, 20% polyester fleece",
    description: "A heavyweight oversized hoodie with a drop shoulder and a roomy kangaroo pocket. Soft inside, structured outside.",
    stock: 40, rating: 4.7, numReviews: 128, soldCount: 560, featured: true, bg: "6C63FF",
  },
  {
    name: "Classic Denim Jacket",
    category: "Men", subcategory: "Jackets",
    price: 89.99, discountPrice: 0,
    colors: ["Blue", "Black"], sizes: CLOTHING_SIZES,
    materials: "100% cotton denim",
    description: "A timeless denim jacket with a slightly boxy fit. Layers over almost everything.",
    stock: 25, rating: 4.6, numReviews: 94, soldCount: 310, featured: true, bg: "3B5BA5",
  },
  {
    name: "Relaxed Fit T-Shirt",
    category: "Men", subcategory: "T-Shirts",
    price: 24.99, discountPrice: 0,
    colors: ["White", "Black", "Yellow", "Coral"], sizes: CLOTHING_SIZES,
    materials: "100% organic cotton",
    description: "An everyday tee with a relaxed cut and a soft, breathable feel.",
    stock: 120, rating: 4.4, numReviews: 210, soldCount: 940, isNewArrival: true, bg: "FF6584",
  },
  {
    name: "Cargo Pants",
    category: "Men", subcategory: "Pants",
    price: 54.99, discountPrice: 0,
    colors: ["Olive", "Black", "Beige"], sizes: CLOTHING_SIZES,
    materials: "65% cotton, 35% nylon",
    description: "Utility cargo pants with six pockets and an adjustable hem. Tough and comfortable.",
    stock: 35, rating: 4.5, numReviews: 76, soldCount: 270, featured: true, bg: "6B7A4B",
  },
  {
    name: "Linen Shirt",
    category: "Men", subcategory: "Shirts",
    price: 49.99, discountPrice: 0,
    colors: ["White", "Sky Blue", "Sand"], sizes: CLOTHING_SIZES,
    materials: "100% linen",
    description: "A lightweight linen shirt that stays cool in summer. Wear it buttoned or open.",
    stock: 30, rating: 4.3, numReviews: 52, soldCount: 180, isNewArrival: true, bg: "00C2A8",
  },
  {
    name: "Slim Chinos",
    category: "Men", subcategory: "Pants",
    price: 59.99, discountPrice: 0,
    colors: ["Navy", "Khaki", "Grey"], sizes: CLOTHING_SIZES,
    materials: "98% cotton, 2% elastane",
    description: "Slim-fit chinos with a little stretch for all-day comfort.",
    stock: 45, rating: 4.2, numReviews: 61, soldCount: 205, bg: "35495E",
  },
  {
    name: "Knit Sweater",
    category: "Women", subcategory: "Sweaters",
    price: 64.99, discountPrice: 49.99,
    colors: ["Cream", "Pink", "Lavender"], sizes: CLOTHING_SIZES,
    materials: "60% cotton, 40% acrylic",
    description: "A chunky knit sweater with a cozy crew neck and ribbed cuffs.",
    stock: 28, rating: 4.8, numReviews: 143, soldCount: 480, featured: true, bg: "FF6584",
  },
  {
    name: "Wide-Leg Jeans",
    category: "Women", subcategory: "Jeans",
    price: 69.99, discountPrice: 0,
    colors: ["Light Blue", "Black"], sizes: CLOTHING_SIZES,
    materials: "100% cotton denim",
    description: "High-rise wide-leg jeans with a clean, straight drape.",
    stock: 33, rating: 4.6, numReviews: 117, soldCount: 390, featured: true, bg: "5B7DB1",
  },
  {
    name: "Floral Summer Dress",
    category: "Women", subcategory: "Dresses",
    price: 74.99, discountPrice: 0,
    colors: ["Yellow", "Coral"], sizes: CLOTHING_SIZES,
    materials: "100% viscose",
    description: "A flowy midi dress with a bright floral print and an adjustable waist tie.",
    stock: 22, rating: 4.5, numReviews: 88, soldCount: 260, isNewArrival: true, bg: "FFD166",
  },
  {
    name: "Pleated Midi Skirt",
    category: "Women", subcategory: "Skirts",
    price: 44.99, discountPrice: 0,
    colors: ["Teal", "Black", "Pink"], sizes: CLOTHING_SIZES,
    materials: "100% polyester",
    description: "A satin-finish pleated skirt that moves beautifully when you walk.",
    stock: 26, rating: 4.4, numReviews: 47, soldCount: 150, isNewArrival: true, bg: "00C2A8",
  },
  {
    name: "Cropped Cardigan",
    category: "Women", subcategory: "Sweaters",
    price: 52.99, discountPrice: 39.99,
    colors: ["Mint", "Cream"], sizes: CLOTHING_SIZES,
    materials: "70% cotton, 30% polyamide",
    description: "A soft cropped cardigan with pearl-style buttons. Perfect over a dress.",
    stock: 18, rating: 4.3, numReviews: 39, soldCount: 120, bg: "7ED6C4",
  },
  {
    name: "Sports Leggings",
    category: "Women", subcategory: "Activewear",
    price: 34.99, discountPrice: 0,
    colors: ["Black", "Purple", "Teal"], sizes: CLOTHING_SIZES,
    materials: "78% nylon, 22% elastane",
    description: "High-waist leggings with four-way stretch and a hidden key pocket.",
    stock: 60, rating: 4.7, numReviews: 201, soldCount: 720, bg: "6C63FF",
  },
  {
    name: "Casual Sneakers",
    category: "Shoes", subcategory: "Sneakers",
    price: 79.99, discountPrice: 0,
    colors: ["White", "Black", "Pink"], sizes: SHOE_SIZES,
    materials: "Canvas upper, rubber sole",
    description: "Clean low-top sneakers with a cushioned insole. Easy to style with anything.",
    stock: 50, rating: 4.6, numReviews: 175, soldCount: 640, featured: true, bg: "252525",
  },
  {
    name: "Leather Ankle Boots",
    category: "Shoes", subcategory: "Boots",
    price: 119.99, discountPrice: 89.99,
    colors: ["Brown", "Black"], sizes: SHOE_SIZES,
    materials: "Genuine leather, rubber sole",
    description: "Classic ankle boots with a side zip and a stable block heel.",
    stock: 15, rating: 4.5, numReviews: 64, soldCount: 140, bg: "7B4B2A",
  },
  {
    name: "Canvas Slip-Ons",
    category: "Shoes", subcategory: "Casual",
    price: 39.99, discountPrice: 0,
    colors: ["Navy", "Red", "White"], sizes: SHOE_SIZES,
    materials: "Canvas, rubber sole",
    description: "Light slip-on shoes that go on in seconds. Great for travel and summer days.",
    stock: 70, rating: 4.1, numReviews: 58, soldCount: 330, isNewArrival: true, bg: "FF6584",
  },
  {
    name: "Crossbody Bag",
    category: "Accessories", subcategory: "Bags",
    price: 45.99, discountPrice: 0,
    colors: ["Black", "Tan", "Lilac"], sizes: ONE_SIZE,
    materials: "Vegan leather, metal hardware",
    description: "A compact crossbody bag with an adjustable strap and two zip compartments.",
    stock: 38, rating: 4.6, numReviews: 99, soldCount: 410, featured: true, bg: "A77BCA",
  },
  {
    name: "Baseball Cap",
    category: "Accessories", subcategory: "Hats",
    price: 19.99, discountPrice: 0,
    colors: ["Black", "White", "Green"], sizes: ONE_SIZE,
    materials: "100% cotton twill",
    description: "A classic six-panel cap with an adjustable back strap.",
    stock: 90, rating: 4.2, numReviews: 70, soldCount: 450, bg: "00C2A8",
  },
  {
    name: "Wool Scarf",
    category: "Accessories", subcategory: "Scarves",
    price: 29.99, discountPrice: 22.99,
    colors: ["Red", "Grey", "Mustard"], sizes: ONE_SIZE,
    materials: "70% wool, 30% acrylic",
    description: "A warm woven scarf with fringed ends. Long enough to wrap twice.",
    stock: 42, rating: 4.4, numReviews: 45, soldCount: 160, bg: "E85D75",
  },
  {
    name: "Kids Graphic Tee",
    category: "Kids", subcategory: "T-Shirts",
    price: 17.99, discountPrice: 0,
    colors: ["Yellow", "Blue", "Green"], sizes: KIDS_SIZES,
    materials: "100% cotton",
    description: "A soft cotton tee with a fun print kids actually want to wear.",
    stock: 80, rating: 4.5, numReviews: 83, soldCount: 380, isNewArrival: true, bg: "FFD166",
  },
  {
    name: "Kids Puffer Jacket",
    category: "Kids", subcategory: "Jackets",
    price: 59.99, discountPrice: 44.99,
    colors: ["Red", "Navy"], sizes: KIDS_SIZES,
    materials: "Polyester shell, recycled fill",
    description: "A light, warm puffer jacket with a hood and zip pockets.",
    stock: 24, rating: 4.7, numReviews: 56, soldCount: 170, bg: "3B5BA5",
  },
  {
    name: "Kids Joggers",
    category: "Kids", subcategory: "Pants",
    price: 27.99, discountPrice: 0,
    colors: ["Grey", "Black"], sizes: KIDS_SIZES,
    materials: "80% cotton, 20% polyester",
    description: "Stretchy joggers with an elastic waist and cuffed ankles.",
    stock: 55, rating: 4.3, numReviews: 41, soldCount: 190, bg: "6B7280",
  },
  {
    name: "Rainbow Party Dress",
    category: "Kids", subcategory: "Dresses",
    price: 34.99, discountPrice: 0,
    colors: ["Multicolor"], sizes: KIDS_SIZES,
    materials: "Cotton blend with tulle layer",
    description: "A twirl-ready dress with a soft tulle skirt in rainbow stripes.",
    stock: 20, rating: 4.8, numReviews: 62, soldCount: 130, featured: true, bg: "FF6584",
  },
];

// Fill in the repeated parts: SKU and two placeholder images per product
export const products = productData.map((item, index) => {
  const { bg, ...rest } = item;
  return {
    ...rest,
    sku: `AH-${String(index + 1).padStart(4, "0")}`,
    images: [img(item.name, bg), img(`${item.name} 2`, "252525")],
  };
});